server.port=8083
spring.application.name=xiaosi-nas
nas.config-path=../config/config.json
nas.storage-root=./storage
nas.language=it-IT

# Italiano (it-IT)
nas.title=小思NAS
nas.welcome=Benvenuto nel servizio小思NAS
user.login=Accesso
user.logout=Disconnessione
user.register=Registrazione
storage.volume=Volume di archiviazione
share.title=Condivisione
system.info=Informazioni sul sistema