server.port=8083
spring.application.name=xiaosi-nas
nas.config-path=../config/config.json
nas.storage-root=./storage
nas.language=ja-JP

# 日本語 (ja-JP)
nas.title=小思NAS
nas.welcome=小思NASサービスへようこそ
user.login=ログイン
user.logout=ログアウト
user.register=登録
storage.volume=ストレージボリューム
share.title=共有
system.info=システム情報