server.port=8083
spring.application.name=xiaosi-nas
nas.config-path=../config/config.json
nas.storage-root=./storage
nas.language=pl-PL

# Polski (pl-PL)
nas.title=小思NAS
nas.welcome=Witamy w usłudze小思NAS
user.login=Logowanie
user.logout=Wylogowanie
user.register=Rejestracja
storage.volume=Wolumin pamięci
share.title=Udostępnij
system.info=Informacje o systemie