server.port=8083
spring.application.name=xiaosi-nas
nas.config-path=../config/config.json
nas.storage-root=./storage
nas.language=ru-RU

# Русский (ru-RU)
nas.title=小思NAS
nas.welcome=Добро пожаловать в службу小思NAS
user.login=Вход
user.logout=Выход
user.register=Регистрация
storage.volume=Объем хранения
share.title=Поделиться
system.info=Системная информация