server.port=8083
spring.application.name=xiaosi-nas
nas.config-path=../config/config.json
nas.storage-root=./storage
nas.language=tr-TR

# Türkçe (tr-TR)
nas.title=小思NAS
nas.welcome=小思NAS hizmetine hoş geldiniz
user.login=Giriş
user.logout=Çıkış
user.register=Kayıt
storage.volume=Depolama hacmi
share.title=Paylaş
system.info=Sistem bilgisi